language: go

sudo: false

go:
  - 1.6
  - 1.7

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/stretchr/testify/assert

script:
  - go test -covermode=count -coverprofile=profile.cov ./rsc
  - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
